---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  secretRef:
    name: github-token
  url: https://github.com/fluxdemo/instavote-deploy.git

---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: github-instavote
  namespace: instavote
spec:
  address: https://github.com/fluxdemo/instavote-deploy
  secretRef:
    name: github-token

---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: result
  namespace: instavote
spec:
  image: dopsdemo/result

---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: vote
  namespace: instavote
spec:
  image: dopsdemo/vote

