---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: instavote
  namespace: instavote
spec:
  gitImplementation: go-git
  interval: 1h
  ref:
    branch: main
  timeout: 20s
  secretRef:
    name: github-token
  url: https://github.com/devopsfoo/instavote-deploy.git

