apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- db-helmrelease.yaml
- db-helmrepository.yaml
- github-instavote-provider.yaml
- instavote-gitrepository.yaml
- redis-kustomization.yaml
- redis-staging-alert.yaml
- result-helmrelease.yaml
- result-imagepolicy.yaml
- result-imagerepository.yaml
- result-imageupdateautomation.yaml
- vote-imagepolicy.yaml
- vote-imagerepository.yaml
- vote-imageupdateautomation.yaml
- vote-kustomization.yaml
- vote-staging-alert.yaml
- worker-kustomization.yaml
- worker-staging-alert.yaml
